name: Generate Wallpaper Gallery

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    # add permissions for the github_token to create a pr
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install deps
        run: pip install pillow

      - name: generate markdown gallery
        run: |
          python gen.py
          python update_readme.py

      - name: create pull request
        # the gh cli is pre-installed on runners
        env:
          # use the default token which has the permissions we set above
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # create a new branch
          git checkout -b update-gallery-${{ github.run_id }}

          # add and commit changes if they exist
          git add README.md WALLPAPER_GALLERY.md
          if ! git diff --cached --quiet; then
            git commit -m "auto: update wallpaper gallery"
            git push origin update-gallery-${{ github.run_id }}
            gh pr create \
              --title "Auto: Update Wallpaper Gallery" \
              --body "Automated wallpaper gallery update." \
              --base main
          else
            echo "no changes to commit."
          fi
