name: Update Wallpaper Gallery

on:
  workflow_dispatch:
  push:
    paths:
      - "*.jpg"
      - "*.jpeg"
      - "*.png"
      - "*.webp"
      - "*.gif"

jobs:
  update-gallery:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate markdown gallery
        run: |
          python gen.py
          python update_readme.py

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.P }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add README.md WALLPAPER_GALLERY.md || true
          git commit -m "auto: update wallpaper gallery" || echo "no changes to commit"
          git push || echo "nothing to push"

