name: Generate Wallpaper Gallery

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.png'
      - '**.jpg'
      - '**.jpeg'
      - '**.gif'
      - '**.webp'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: generate markdown gallery
        run: |
          python gen.py
          python update_readme.py

      - name: commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md WALLPAPER_GALLERY.md
          # commit only if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "auto: update wallpaper gallery"
            git push
          else
            echo "no changes to commit."
          fi
