name: Generate Wallpaper Gallery

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.png'
      - '**.jpg'
      - '**.jpeg'
      - '**.gif'
      - '**.webp'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install deps
        run: pip install pillow

      - name: generate markdown gallery
        run: |
          python gen.py
          python update_readme.py

      - name: create and auto-merge pull request
        env:
          # use the default token which has the permissions we set above
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # create a new branch
          BRANCH_NAME="auto-gallery-update/${{ github.run_id }}"
          git checkout -b $BRANCH_NAME

          # add and commit changes if they exist
          git add README.md WALLPAPER_GALLERY.md
          if ! git diff --cached --quiet; then
            echo "changes found, creating pull request..."
            git commit -m "auto: update wallpaper gallery"
            git push origin $BRANCH_NAME
            
            # create the pull request
            gh pr create \
              --title "Auto: Update Wallpaper Gallery" \
              --body "Automated wallpaper gallery update." \
              --base main
              
            # merge the pull request automatically
            gh pr merge $BRANCH_NAME --squash --delete-branch
          else
            echo "no changes to commit."
          fi
